version: '3.6'

services:

  tor:
    image: dperson/torproxy
    restart: on-failure
    ports:
      - "9050:9050"
      - "9051:9051"
    environment:
      - PASSWORD=admin

  py_ip:
    build: .
    restart: on-failure
    depends_on:
      - tor
    volumes:
     - ./log:/var/log/py

